import Head from 'next/head'
import San from '../components/san'
// import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Senyum Anak Nusantara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <San />
    </div>
  )
}
